### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by aoyawale** [allox/django-base-template-1.8#2]
hello,

I tried to install this and got this error 

(gaming) jcasanova@casanova-master:~/Desktop/git_test/gaming_django/gaming/src$ ./manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fc80a5986a8>
Traceback (most recent call last):
  File "/home/jcasanova/Desktop/git_test/gaming_django/gaming/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(_args, *_kwargs)
  File "/home/jcasanova/Desktop/git_test/gaming_django/gaming/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/home/jcasanova/Desktop/git_test/gaming_django/gaming/lib/python3.5/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/jcasanova/Desktop/git_test/gaming_django/gaming/lib/python3.5/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/jcasanova/Desktop/git_test/gaming_django/gaming/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/jcasanova/Desktop/git_test/gaming_django/gaming/lib/python3.5/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/jcasanova/Desktop/git_test/gaming_django/gaming/lib/python3.5/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/jcasanova/Desktop/git_test/gaming_django/gaming/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.**dict**[self.name] = self.func(instance)
  File "/home/jcasanova/Desktop/git_test/gaming_django/gaming/lib/python3.5/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/jcasanova/Desktop/git_test/gaming_django/gaming/lib/python3.5/site-packages/django/utils/functional.py", line 35, in **get**
    res = instance.**dict**[self.name] = self.func(instance)
  File "/home/jcasanova/Desktop/git_test/gaming_django/gaming/lib/python3.5/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/jcasanova/Desktop/git_test/gaming_django/gaming/lib/python3.5/importlib/**init**.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/jcasanova/Desktop/git_test/gaming_django/gaming/src/mainapp/urls.py", line 22, in <module>
    url(r'', include('base.urls')),
  File "/home/jcasanova/Desktop/git_test/gaming_django/gaming/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/jcasanova/Desktop/git_test/gaming_django/gaming/lib/python3.5/importlib/**init**.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/jcasanova/Desktop/git_test/gaming_django/gaming/src/base/urls.py", line 4, in <module>
    from views import home
**ImportError: No module named 'views'**

**Comment by Alex-CodeLab** [comment]
thanks for mentioning this.

seems to be an issue only with python3.  
(in src/base/urls.py )
anyway.. it should be fixed now
